---
- name: "(Setup: All OSs Besides Alpine Linux) Setup NGINX Plus License"
  block:

    - name: "(Setup: All OSs Besides Alpine Linux) Create SSL Directory"
      file:
        path: '{{ nginx_ssl_dir }}/nginx'
        mode: 0755
        state: directory

    - name: "(Setup: All OSs Besides Alpine Linux) Copy NGINX Plus Certificate and License Key"
      copy:
        src: "{{ item }}"
        dest: '{{ nginx_ssl_dir }}/nginx'
        decrypt: yes
        mode: 0640
      with_items:
        - "{{ nginx_license.certificate }}"
        - "{{ nginx_license.key }}"

  when: ansible_distribution != "Alpine"

- name: "(Setup: Alpine Linux) Setup NGINX Plus License"
  block:

    - name: "(Setup: Alpine Linux) Create APK Directory"
      file:
        path: /etc/apk
        mode: 0755
        state: directory

    - name: "(Setup: Alpine Linux) Copy NGINX Plus Key"
      copy:
        src: "{{ nginx_license.key }}"
        dest: /etc/apk/cert.key
        mode: 0640
        decrypt: yes

    - name: "(Setup: Alpine Linux) Copy NGINX Plus Certificate"
      copy:
        src: "{{ nginx_license.certificate }}"
        dest: /etc/apk/cert.pem
        mode: 0644
        decrypt: yes

  when: ansible_distribution == "Alpine"
