---
- name: "(Setup: CentOS/RedHat/Oracle Linux) Setup NGINX Plus Repository"
  yum_repository:
    name: nginx-plus
    baseurl: >-
      https://plus-pkgs.nginx.com/centos/{{ (ansible_distribution_version | float >= 7.4 and ansible_distribution_version | float < 8.0)
      | ternary(ansible_distribution_major_version | int, 7.4) }}/$basearch/
    description: NGINX Plus Repository
    sslclientcert: '{{ nginx_ssl_dir }}/nginx/nginx-repo.crt'
    sslclientkey: '{{ nginx_ssl_dir }}/nginx/nginx-repo.key'
    enabled: yes
    gpgcheck: yes
    state: "{{ nginx_license_status | default ('present') }}"
  when: ansible_distribution != "Amazon"

- name: "(Setup: Amazon Linux) Setup NGINX Plus Repository"
  yum_repository:
    name: nginx-plus
    baseurl: >-
      https://plus-pkgs.nginx.com/amzn{{ (ansible_distribution_version == "2")
      | ternary('2', '') }}/$releasever/$basearch
    description: NGINX Plus Repository
    sslclientcert: '{{ nginx_ssl_dir }}/nginx/nginx-repo.crt'
    sslclientkey: '{{ nginx_ssl_dir }}/nginx/nginx-repo.key'
    enabled: yes
    gpgcheck: yes
    state: "{{ nginx_license_status | default ('present') }}"
  when: ansible_distribution == "Amazon"
